SUPABASE_URL = "https://thosxcqpbjurpdobcfim.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3N4Y3FwYmp1cnBkb2JjZmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTkyODQsImV4cCI6MjA2OTMzNTI4NH0.70Kb-t287t51fyFbHodDlC4oXVvnTTZ1PE14uPc14eg"
GEMINI_API_KEY = "AIzaSyD_2LlbeBlfwWH-TLAT0_jecWWN0yiyidQ"
OPENAI_API_KEY = "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"
